# toml-docs-start main
title = "Tt200411's Personal Website"
copyright = "Copyright © 2025 Tt200411."
enableGitInfo = true
# toml-docs-end main

# additional settings
baseURL = "https://tt200411.github.io/"
canonifyURLs = false
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
summaryLength = 20

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# toml-docs-start timeout
timeout = "180s"
# toml-docs-end timeout

# toml-docs-start language
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# toml-docs-end language

# toml-docs-start headers
[outputFormats]
  [outputFormats.server]
    mediaType = "application/toml"
    baseName = "server"
    isPlainText = true
    notAlternative = true
    permalinkable = true
    root = true
  [outputFormats.netlify]
    mediaType = "application/toml"
    baseName = "netlify"
    isPlainText = true
    notAlternative = true
    permalinkable = true
    root = true
# toml-docs-end headers

  [outputFormats.XML]
    isPlainText = false
    mediaType = "application/xml"
    isHtml = false
    noUgly = true
    permalinkable = false
    name = "xml"

# toml-docs-start redirect
  [outputFormats.REDIR]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

[mediaTypes."text/netlify"]
delimiter = ""
# toml-docs-end redirect

# toml-docs-start outputs
[outputs]
home = ["HTML", "RSS", "REDIR", "netlify", "server"]
# toml-docs-end outputs

# toml-docs-start build
[build]
  writeStats = true
# toml-docs-end build
  
[taxonomies]
  tag = 'tags'

[pagination]
  pagerSize = 9

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.x]
    disableInlineCSS = true
  [services.googleAnalytics]
    # ID = "G-xxxxxxxxxx"

[minify]
  [minify.tdewolff.js]
    keepVarNames = true
    precision = 0
    version = 2022
  [minify.tdewolff.html]
    keepWhitespace = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = 'component-library'
    target = 'layouts/partials/bookshop'
    includeFiles = ['**/*.hugo.html']
  [[module.mounts]]
    source = 'component-library'
    target = 'data/structures'
    includeFiles = ['**/*.bookshop.yml']
  [[module.mounts]]
    source = 'component-library'
    target = 'assets/bookshop'
  [[module.mounts]]
    source = 'component-library'
    target = 'assets/scss/modules/bookshop'
    includeFiles = ['**/*.scss']
    excludeFiles = ['bookshop.scss']
  [[module.mounts]]
    source = 'component-library/bookshop.scss'
    target = 'assets/scss/bookshop.scss'
  [[module.mounts]]
    source = 'component-library/helpers'
    target = 'layouts/partials/_bookshop/helpers'
  # ensures main package.json is always available, even when using workspaces
  # in workspaces, the package.json is pointing to the first imported module
  [[module.mounts]]
    source = "package.json"
    target = "assets/data/package-hinode.json"
  [[module.mounts]]
    source = "netlify.toml"
    target = "assets/config/netlify.toml"
# toml-docs-start modules
  [[module.imports]]
    path = "github.com/cloudcannon/bookshop/hugo/v3"
  [[module.imports]]
    path = "github.com/gethinode/mod-bootstrap"
  [[module.imports]]
    path = "github.com/gethinode/mod-csp"
  [[module.imports]]
    path = "github.com/gethinode/mod-flexsearch/v3"
  [[module.imports]]
    path = "github.com/gethinode/mod-fontawesome/v2"
  [[module.imports]]
    path = "github.com/gethinode/mod-google-analytics"
  [[module.imports]]
    path = "github.com/gethinode/mod-katex"
  [[module.imports]]
    path = "github.com/gethinode/mod-leaflet"
  [[module.imports]]
    path = "github.com/gethinode/mod-lottie"
  [[module.imports]]
    path = "github.com/gethinode/mod-mermaid/v3"
  [[module.imports]]
    path = "github.com/gethinode/mod-simple-datatables/v2"
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v4"
# toml-docs-end modules

# toml-docs-start segments
[segments]
  [segments.headers]
    [[segments.headers.includes]]
       kind = '{home}'
       output = '{netlify,server}'
# toml-docs-end segments
