# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Separator
  description: Inserts a horizontal page section separator
  icon: horizontal_rule
  tags: []

blueprint:
